#!/usr/bin/python

import sys
import prog1_1

def checkCommandLine():
    for cmd in sys.argv[1:]:
        pass

def encrypt():
    pass

def decrypt():
    pass

if __name__ == "__main__":
    print hi
    checkCommandLine()
