#!/usr/bin/python

import sys
import re

def checkCommandLine():
    filename = ''
    enc_bool = True # True if encrypting
    key_bool = True # True if key is in binary
    args = ''
    for cmd in sys.argv[1:]:
        if cmd == '-e':
            pass
        elif cmd == '-d':
            enc_bool = False
        elif cmd == '-x':
            key_bool = False
        elif cmd == '-b':
            pass
        elif re.match(r'-k.*', cmd, flags=0):
            if len(cmd) is not 2:
                filename = cmd[2:]
            else:
                raise ValueError('Please enter a valid filename')
        else:
            args += cmd
    if not sys.stdin.isatty():
        for line in sys.stdin.read():
            args += line
    checkInput(enc_bool, key_bool, filename, args)

def checkInput(enc_bool, key_bool, filename, args):
    std_input = []
    if all(c in ['0', '1'] for c in list(args.replace(' ', ''))):
        std_input = [args[i:i+4] for i in range(0, len(args), 4)]
    elif all(c in ['0', '1', '2', '3', '4', '5',
                   '6', '7', '8', '9', 'a', 'b',
                   'c', 'd', 'e', 'f', 'A', 'B',
                   'C', 'D', 'E', 'F']
             for c in list(args.replace(' ', ''))):
        std_input = list(args.replace(' ', ''))       
    else:
        args = [int(format(ord(i), '08b'), 2) for i in list(args)]
        for b in args:
            std_input.append(hex(int(bin(b >> 4)[2:], 2))[2:])
            std_input.append(hex(int(bin(b & 15)[2:], 2))[2:])
    key = processKey(key_bool, filename)
    encrypt_or_decrypt(enc_bool, key, std_input)
    
def processKey(key_bool, filename):
    keyfile = open(filename, 'r')
    key_vals = keyfile.read().replace(' ', '')
    key = {}
    temp = []
    if key_bool:
        key_vals = [int(format(ord(i), '04b'), 2) for i in list(key_vals)]
        for b in key_vals:
            temp.append(hex(int(bin(b >> 4)[2:], 2))[2:])
            temp.append(hex(int(bin(b & 15)[2:], 2))[2:])
        for k in temp:
            key[hex(temp.index(k))[2:]] = k.upper()
    else:
        if len(key_vals) > 16:
            raise ValueError('Key is too long')
        elif not isUnique(key_vals):
            raise ValueError('Key is not unique')
        key_vals = list(key_vals)
        for k in key_vals:
            key[hex(key_vals.index(k))[2:]] = k.upper()
    return key

def encrypt_or_decrypt(enc_bool, key, std_input):
    output = []
    if enc_bool:
        for val in std_input:
            output.append(key[val])
    else:
        for val in std_input:
            for k, v in key.items():
                if val.lower() == v.lower():
                    output.append(k)    
    x = 0
    y = 0
    output = [''.join(x) for x in zip(output[0::2], output[1::2])]
    for o in output:
        sys.stdout.write(chr(int(o, 16)))
def isUnique(s):
    def _contains(string, char):
        for c in string:
            if c == char:
                return True
        return False
    for index in range(len(s)):
        if _contains(s[:index], s[index]):
            return False
    return True    

if __name__ == "__main__":
    checkCommandLine()
