#! /usr/bin/python

import sys

def check_command_line():
    pad_bool = True
    block_size = 8
    pad_input = ''
    for args in sys.argv[1:]:
        if args == '-p':
            pass
        elif args == '-u':
            pad_bool = False
        elif args[:2] == '-b':
            if args[2:] == '':
                raise ValueError('Option -b cannot be empty')
            elif not args[2:].isdigit():
                raise ValueError('Please input integers')
            else:
                block_size = int(args[2:])
        else:
            pad_input += args
    pad_input = [ord(i) for i in pad_input]
    if pad_bool:
        pad(pad_input, block_size)
    else:
        unpad(pad_input, pad_size)
        
def pad(pad_input, block_size):
    pad_size = block_size - (len(pad_input) % block_size)
    for i in range(0, pad_size, 1):
        pad_input.append(pad_size)
    for x in pad_input:
        sys.stdout.write(chr(x))
        
def unpad(pad_input, block_size):
    if not pad_input[:1] = pad_input[block_size-2:1]:
        raise ValueError('The last two characters are not the same, there appears to be no padding')
    else:
        print 'hi'
    
if __name__ == '__main__':
    check_command_line()
